#!/usr/bin/env python3
import sys
import os
import importlib
import atexit
import subprocess

from plot import Plot
import turtle as t

mtime = None

def check_update(filename, module, p: Plot):
    global mtime
    new_mtime = os.stat(os.path.abspath(filename)).st_mtime
    if mtime is None or new_mtime > mtime:
        mtime = new_mtime
        importlib.reload(module)
        module.main(p)
        t.update()
    t._Screen._root.after(100, check_update, filename, module, p)

def main():
    filename = sys.argv[1]
    module_name = os.path.splitext(filename)[0]
    module = importlib.import_module(module_name)

    plotter_enabled = len(sys.argv) > 2 and sys.argv[2] == '--plot'
    p = Plot(plotter_enabled)
    if plotter_enabled:
        # prevent screen from sleeping
        proc = subprocess.Popen(['caffeinate', '-d'])
        atexit.register(self._caff_proc.terminate)

        module.main(p)

        proc.terminate()
        p.done()
    else:
        check_update(filename, module, p)
        p.done()

if __name__ == "__main__":
    main()