#!/usr/bin/env python3
import os.path
import importlib
import atexit
import subprocess
import traceback
from datetime import datetime
from argparse import ArgumentParser

from plot import Plot
import turtle as t

class PlotWatcher():

    def __init__(self, p: Plot, filename, plot_args):
        self.p = p
        self.filename = filename
        self.plot_args = plot_args
        self.module = None
        self.mtime = None
        self.drawing = False

    def redraw_plot(self):
        if self.drawing:
            return False
        print('reloading plot')
        try:
            if self.module:
                importlib.reload(self.module)
            else:
                module_name = os.path.splitext(self.filename)[0].replace('/', '.')
                self.module = importlib.import_module(module_name)
            self.drawing = True
            self.module.main(self.p, *self.plot_args)
        except:
            traceback.print_exc()
        self.drawing = False
        t.update()
        return True
    
    def _tick(self):
        new_mtime = os.path.getmtime(os.path.abspath(self.filename))
        if self.mtime is None or new_mtime > self.mtime:
            if self.redraw_plot():
                self.mtime = new_mtime
        t._Screen._root.after(200, self._tick)

    def start(self):
        t.onscreenclick(lambda _x, _y: self.redraw_plot())
        self._tick()

def main(args, plot_args):
    p = Plot(args.plotter_enabled)
    if args.plotter_enabled:
        module_name = os.path.splitext(args.filename)[0].replace('/', '.')
        module = importlib.import_module(module_name)
        # prevent screen from sleeping
        proc = subprocess.Popen(['caffeinate', '-d'])
        atexit.register(proc.terminate)

        start_time = datetime.now()
        module.main(p, *plot_args)
        print('total time elapsed:', datetime.now()-start_time)

        proc.terminate()
        p.done()
    else:
        PlotWatcher(p, args.filename, plot_args).start()
        p.done()

if __name__ == "__main__":
    p = ArgumentParser()
    p.add_argument('filename')
    p.add_argument('-p', '--plot', dest='plotter_enabled', action='store_true')

    args, plot_args = p.parse_known_args()
    main(args, plot_args)